/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatNewRouteImport } from './routes/chat/new'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as ChatIdSharedRouteImport } from './routes/chat/$id/shared'
import { Route as ChatIdReportRouteImport } from './routes/chat/$id/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdSharedRoute = ChatIdSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => ChatIdRoute,
} as any)
const ChatIdReportRoute = ChatIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ChatIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/$id': typeof ChatIdRouteWithChildren
  '/chat/new': typeof ChatNewRoute
  '/chat/$id/report': typeof ChatIdReportRoute
  '/chat/$id/shared': typeof ChatIdSharedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$id': typeof ChatIdRouteWithChildren
  '/chat/new': typeof ChatNewRoute
  '/chat/$id/report': typeof ChatIdReportRoute
  '/chat/$id/shared': typeof ChatIdSharedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/$id': typeof ChatIdRouteWithChildren
  '/chat/new': typeof ChatNewRoute
  '/chat/$id/report': typeof ChatIdReportRoute
  '/chat/$id/shared': typeof ChatIdSharedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/chat/$id' | '/chat/new' | '/chat/$id/report' | '/chat/$id/shared'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$id' | '/chat/new' | '/chat/$id/report' | '/chat/$id/shared'
  id:
    | '__root__'
    | '/'
    | '/chat/$id'
    | '/chat/new'
    | '/chat/$id/report'
    | '/chat/$id/shared'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatIdRoute: typeof ChatIdRouteWithChildren
  ChatNewRoute: typeof ChatNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/new': {
      id: '/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id/shared': {
      id: '/chat/$id/shared'
      path: '/shared'
      fullPath: '/chat/$id/shared'
      preLoaderRoute: typeof ChatIdSharedRouteImport
      parentRoute: typeof ChatIdRoute
    }
    '/chat/$id/report': {
      id: '/chat/$id/report'
      path: '/report'
      fullPath: '/chat/$id/report'
      preLoaderRoute: typeof ChatIdReportRouteImport
      parentRoute: typeof ChatIdRoute
    }
  }
}

interface ChatIdRouteChildren {
  ChatIdReportRoute: typeof ChatIdReportRoute
  ChatIdSharedRoute: typeof ChatIdSharedRoute
}

const ChatIdRouteChildren: ChatIdRouteChildren = {
  ChatIdReportRoute: ChatIdReportRoute,
  ChatIdSharedRoute: ChatIdSharedRoute,
}

const ChatIdRouteWithChildren =
  ChatIdRoute._addFileChildren(ChatIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatIdRoute: ChatIdRouteWithChildren,
  ChatNewRoute: ChatNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
